# Auto schema

# --- !Ups
CREATE TABLE IF NOT EXISTS auto (
  id SERIAL PRIMARY KEY,
  VIN CHAR(17) UNIQUE,
  number CHAR(45) NOT NULL DEFAULT NULL,
  make CHAR(45) NOT NULL DEFAULT NULL,
  color CHAR(15) NOT NULL DEFAULT NULL,
  year INT NOT NULL DEFAULT NULL);

# --- !Downs
DROP TABLE auto;