# Auto schema

# --- !Ups
CREATE TABLE IF NOT EXISTS auto (
  id SERIAL PRIMARY KEY,
  VIN VARCHAR(17) UNIQUE,
  number VARCHAR(45) NOT NULL DEFAULT NULL,
  make VARCHAR(45) NOT NULL DEFAULT NULL,
  color VARCHAR(15) NOT NULL DEFAULT NULL,
  year INT NOT NULL DEFAULT NULL);

# --- !Downs
DROP TABLE auto;